import os

from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from .common import GREY, NEG_RED, PAGE_HEIGHT, PAGE_WIDTH, POS_GREEN, ROW_ALT, RULE, SLATE, TABLE_HEAD_BG, WHITE, WINE
from .common import make_style


def write_date_range_summary_pdf(
    output_path,
    meta_rows,
    overview_rows,
    invoice_rows,
    sell_rows,
    finance_rows,
    title="Date Range Summary",
):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    generated_by = "Nagarjun"
    date_from = ""
    date_to = ""
    generated_at = ""
    if meta_rows:
        for row in meta_rows:
            if len(row) < 2:
                continue
            key = str(row[0] or "").strip().lower()
            value = str(row[1] or "").strip()
            if key == "generated_by" and value:
                generated_by = value
            elif key == "date_from":
                date_from = value
            elif key == "date_to":
                date_to = value
            elif key == "generated_at":
                generated_at = value

    def fmt(value):
        try:
            return f"{float(value):,.2f}"
        except (TypeError, ValueError):
            return str(value or "")

    header_height = 36 * mm
    footer_height = 16 * mm
    margin = 12 * mm

    def draw_chrome(canvas_obj: canvas.Canvas, doc):
        canvas_obj.saveState()
        canvas_obj.setFillColor(WHITE)
        canvas_obj.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, fill=1, stroke=0)

        canvas_obj.setFillColor(WINE)
        canvas_obj.setFont("Helvetica-Bold", 16)
        canvas_obj.drawString(margin, PAGE_HEIGHT - 15 * mm, "Royal Wines")

        canvas_obj.setFillColor(SLATE)
        canvas_obj.setFont("Helvetica-Bold", 12)
        canvas_obj.drawRightString(PAGE_WIDTH - margin, PAGE_HEIGHT - 15 * mm, title.upper())

        canvas_obj.setFillColor(GREY)
        canvas_obj.setFont("Helvetica", 8)
        canvas_obj.drawString(margin, PAGE_HEIGHT - 21 * mm, f"Range: {date_from} to {date_to}")
        canvas_obj.drawString(margin, PAGE_HEIGHT - 26 * mm, f"Generated At: {generated_at}")
        canvas_obj.drawRightString(PAGE_WIDTH - margin, PAGE_HEIGHT - 21 * mm, f"Generated By: {generated_by}")

        canvas_obj.setStrokeColor(RULE)
        canvas_obj.setLineWidth(0.8)
        canvas_obj.line(margin, PAGE_HEIGHT - 30 * mm, PAGE_WIDTH - margin, PAGE_HEIGHT - 30 * mm)

        canvas_obj.line(margin, 12 * mm, PAGE_WIDTH - margin, 12 * mm)
        canvas_obj.drawString(margin, 7 * mm, "System Generated Document")
        canvas_obj.drawRightString(PAGE_WIDTH - margin, 7 * mm, f"Page {doc.page}")
        canvas_obj.restoreState()

    doc = BaseDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=margin,
        rightMargin=margin,
        topMargin=header_height,
        bottomMargin=footer_height,
    )
    frame = Frame(
        doc.leftMargin,
        doc.bottomMargin,
        doc.width,
        doc.height,
        id="main",
        leftPadding=0,
        rightPadding=0,
        topPadding=0,
        bottomPadding=0,
    )
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=draw_chrome)])

    normal = make_style("normal")
    right = make_style("right", alignment=TA_RIGHT)
    center = make_style("center", alignment=TA_CENTER)
    head = make_style("head", fontName="Helvetica-Bold", alignment=TA_CENTER)
    section = make_style("section", fontName="Helvetica-Bold", fontSize=10, textColor=WINE, leading=16)
    good = make_style("good", fontName="Helvetica-Bold", textColor=POS_GREEN, alignment=TA_RIGHT)
    bad = make_style("bad", fontName="Helvetica-Bold", textColor=NEG_RED, alignment=TA_RIGHT)

    story = []

    story.append(Paragraph("Overview", section))
    story.append(Spacer(1, 4))
    overview_table_rows = [[Paragraph("Metric", head), Paragraph("Value", head)]]
    for row in overview_rows or []:
        label = str(row[0] if len(row) > 0 else "")
        value = row[1] if len(row) > 1 else ""
        style = right
        if "balance" in label.lower():
            style = bad if float(value or 0.0) < 0 else good
        overview_table_rows.append([
            Paragraph(label, normal),
            Paragraph(fmt(value), style),
        ])
    overview_table = Table(overview_table_rows, colWidths=[110 * mm, 70 * mm], repeatRows=1)
    overview_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), TABLE_HEAD_BG),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, ROW_ALT]),
        ("GRID", (0, 0), (-1, -1), 0.4, RULE),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]))
    story.append(overview_table)
    story.append(Spacer(1, 14))

    def add_section(title_text, headers, rows, col_widths):
        story.append(Paragraph(title_text, section))
        story.append(Spacer(1, 4))
        table_rows = [[Paragraph(str(header or ""), head) for header in headers]]
        if rows:
            for row in rows:
                converted = []
                for value in row:
                    text = fmt(value) if isinstance(value, (int, float)) else str(value or "")
                    converted.append(Paragraph(text, normal))
                table_rows.append(converted)
        else:
            table_rows.append([
                Paragraph("No data in selected range", center),
                *[Paragraph("", center) for _ in headers[1:]]
            ])

        table = Table(table_rows, colWidths=col_widths, repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), TABLE_HEAD_BG),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, ROW_ALT]),
            ("GRID", (0, 0), (-1, -1), 0.4, RULE),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(table)
        story.append(Spacer(1, 14))

    add_section(
        "Invoice Summary",
        ["Invoice Date", "Invoice Number", "Net Value", "Total Value"],
        invoice_rows,
        [35 * mm, 55 * mm, 40 * mm, 40 * mm],
    )
    add_section(
        "Sell Report Summary",
        ["Report Date", "Items", "Sell Amount", "Final Balance"],
        sell_rows,
        [40 * mm, 30 * mm, 50 * mm, 50 * mm],
    )
    add_section(
        "Finance Entries",
        ["Report Date", "Sell Amount", "Expenses", "Outside Income", "Final Balance"],
        finance_rows,
        [32 * mm, 34 * mm, 34 * mm, 40 * mm, 40 * mm],
    )

    doc.build(story)
    return output_path
