import os

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.platypus import BaseDocTemplate, Frame, PageTemplate, Paragraph, Spacer, Table, TableStyle

W, H = A4
M = 12 * mm

NAVY = colors.HexColor("#1B3A6B")
SLATE = colors.HexColor("#2E2E3A")
GREY = colors.HexColor("#6B6B80")
RULE = colors.HexColor("#C8D0DE")
ALT = colors.HexColor("#F4F6FB")
TH = colors.HexColor("#D9E2F0")
WHITE = colors.white
RED = colors.HexColor("#B00020")
GREEN = colors.HexColor("#1E6B3A")


def ps(name, **kw):
    defaults = dict(fontName="Helvetica", fontSize=8.5, textColor=SLATE, leading=12)
    defaults.update(kw)
    return ParagraphStyle(name, **defaults)


def fmt(v):
    try:
        return f"{float(v):,.2f}"
    except Exception:
        return str(v or "")


def _normalize_payload(meta_rows, items_rows, totals_rows):
    if isinstance(meta_rows, dict):
        return {
            "invoice_meta": dict(meta_rows.get("invoice_meta") or {}),
            "retailer": dict(meta_rows.get("retailer") or {}),
            "licensee": dict(meta_rows.get("licensee") or {}),
            "totals": dict(totals_rows or {}),
            "items": list(items_rows or []),
        }

    payload = {
        "invoice_meta": {"invoice_number": "", "invoice_date": ""},
        "retailer": {"name": "", "code": ""},
        "licensee": {"pan": ""},
        "totals": {},
        "items": [],
    }

    for row in meta_rows or []:
        if len(row) < 2:
            continue
        key = str(row[0] or "").strip().lower()
        value = row[1]
        if key == "invoice number":
            payload["invoice_meta"]["invoice_number"] = str(value or "")
        elif key == "invoice date":
            payload["invoice_meta"]["invoice_date"] = str(value or "")
        elif key == "retailer":
            text = str(value or "")
            if "(" in text and text.endswith(")"):
                name, code = text.rsplit("(", 1)
                payload["retailer"]["name"] = name.strip()
                payload["retailer"]["code"] = code[:-1].strip()
            else:
                payload["retailer"]["name"] = text

    for row in totals_rows or []:
        if len(row) < 2:
            continue
        payload["totals"][str(row[0] or "").strip().lower().replace(" ", "_")] = row[1]

    for index, row in enumerate(items_rows or []):
        if index == 0:
            continue
        payload["items"].append({
            "sl_no": row[0] if len(row) > 0 else "",
            "brand_number": "",
            "brand_name": row[1] if len(row) > 1 else "",
            "product_type": "",
            "pack_type": "",
            "pack_size_case": "",
            "pack_size_quantity_ml": str(row[2] if len(row) > 2 else "").split("/")[:1][0],
            "cases_delivered": row[3] if len(row) > 3 else "",
            "bottles_delivered": row[4] if len(row) > 4 else "",
            "rate_per_case": "",
            "unit_rate_per_bottle": "",
            "total_amount": row[5] if len(row) > 5 else "",
        })

    return payload


def _draw_chrome(c: canvas.Canvas, doc):
    c.saveState()
    data = doc._data
    inv = data["invoice_meta"]

    c.setFillColor(WHITE)
    c.rect(0, 0, W, H, fill=1, stroke=0)

    header_height = 20 * mm
    header_y = H - header_height

    c.setFillColor(SLATE)
    c.setFont("Helvetica-Bold", 13)
    c.drawString(M, H - 10 * mm, "Royal Wines")

    c.setFillColor(GREY)
    c.setFont("Helvetica", 7.5)
    c.drawString(M, H - 16 * mm, "Generated by Royal Wines  |  Nagarjun Reddy")

    c.setFillColor(SLATE)
    c.setFont("Helvetica-Bold", 8)
    c.drawRightString(W - M, H - 10 * mm, str(inv.get("invoice_number", "")))

    c.setFillColor(GREY)
    c.setFont("Helvetica", 8)
    c.drawRightString(W - M, H - 16 * mm, str(inv.get("invoice_date", "")))

    c.setStrokeColor(RULE)
    c.setLineWidth(0.8)
    c.line(M, header_y, W - M, header_y)

    c.setStrokeColor(RULE)
    c.setLineWidth(0.4)
    c.line(M, 10 * mm, W - M, 10 * mm)
    c.setFont("Helvetica", 7)
    c.setFillColor(GREY)
    c.drawString(M, 7 * mm, "System Generated Document")
    c.drawRightString(W - M, 7 * mm, f"Page {doc.page}")

    c.restoreState()


def write_invoice_pdf(output_path, meta_rows, items_rows, totals_rows, title="Invoice Report"):
    data = _normalize_payload(meta_rows, items_rows, totals_rows)
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    doc = BaseDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=M,
        rightMargin=M,
        topMargin=24 * mm,
        bottomMargin=16 * mm,
    )
    doc._data = data

    frame = Frame(
        doc.leftMargin,
        doc.bottomMargin,
        doc.width,
        doc.height,
        id="main",
        leftPadding=0,
        rightPadding=0,
        topPadding=0,
        bottomPadding=0,
    )
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=_draw_chrome)])

    retailer = data["retailer"]
    licensee = data["licensee"]
    totals = data["totals"]
    items = data["items"]

    normal = ps("n")
    right = ps("r", alignment=TA_RIGHT)
    center = ps("c", alignment=TA_CENTER)
    th = ps("th", fontName="Helvetica-Bold", fontSize=8, alignment=TA_CENTER)
    tl = ps("tl", fontName="Helvetica-Bold", fontSize=8)
    bold = ps("b", fontName="Helvetica-Bold")
    grey = ps("g", textColor=GREY, fontSize=8)
    small = ps("sm", fontSize=8)
    small_bold = ps("smb", fontSize=8, fontName="Helvetica-Bold")

    story = []

    meta_table = Table(
        [[
            Paragraph("Retailer Name", grey), Paragraph(str(retailer.get("name", "")), bold),
            Paragraph("Retailer Code", grey), Paragraph(str(retailer.get("code", "")), normal),
        ], [
            Paragraph("PAN", grey), Paragraph(str(licensee.get("pan", "")), normal),
            Paragraph("", grey), Paragraph("", normal),
        ]],
        colWidths=[28 * mm, 60 * mm, 28 * mm, 67 * mm],
    )
    meta_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8F9FC")),
        ("BOX", (0, 0), (-1, -1), 0.4, RULE),
        ("INNERGRID", (0, 0), (-1, -1), 0.3, RULE),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 6))

    item_rows = [[
        Paragraph("#", th),
        Paragraph("Brand\nNo.", th),
        Paragraph("Brand Name", tl),
        Paragraph("Type", th),
        Paragraph("Pack\nType", th),
        Paragraph("Pack Qty\n/ Size (ml)", th),
        Paragraph("Cases\nDel.", th),
        Paragraph("Btls\nDel.", th),
        Paragraph("Rate/Case\n(Rs.)", th),
        Paragraph("Unit Rate\n/ Btl", th),
        Paragraph("Total\n(Rs.)", th),
    ]]
    for item in items:
        item_rows.append([
            Paragraph(str(item.get("sl_no", "")), center),
            Paragraph(str(item.get("brand_number", "")), center),
            Paragraph(str(item.get("brand_name", "")), normal),
            Paragraph(str(item.get("product_type", "")), center),
            Paragraph(str(item.get("pack_type", "")), center),
            Paragraph(f"{item.get('pack_size_case', '')}/{item.get('pack_size_quantity_ml', '')}ml", center),
            Paragraph(str(item.get("cases_delivered", "")), center),
            Paragraph(str(item.get("bottles_delivered", "")), center),
            Paragraph(fmt(item.get("rate_per_case")), right),
            Paragraph(fmt(item.get("unit_rate_per_bottle")), right),
            Paragraph(fmt(item.get("total_amount")), right),
        ])

    items_table = Table(
        item_rows,
        colWidths=[7 * mm, 12 * mm, 53 * mm, 11 * mm, 10 * mm, 16 * mm, 10 * mm, 9 * mm, 18 * mm, 16 * mm, 17 * mm],
        repeatRows=1,
    )
    items_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), TH),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, ALT]),
        ("GRID", (0, 0), (-1, -1), 0.35, RULE),
        ("LINEBELOW", (0, 0), (-1, 0), 0.8, NAVY),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(items_table)
    story.append(Spacer(1, 8))

    credit_balance = totals.get("retailer_credit_balance", 0) or 0
    balance_color = RED if float(credit_balance or 0) < 0 else GREEN

    finance_rows = []
    for label, key, is_bold in [
        ("e-Challan Amount", "e_challan_amount", False),
        ("Previous Credit", "previous_credit", False),
        ("Sub Total", "sub_total", True),
        ("Special Excise Cess", "special_excise_cess", False),
        ("TCS", "tcs", False),
        ("New Retailer Professional Tax", "new_retailer_professional_tax", False),
        ("Retail Shop Excise Turnover Tax", "retail_shop_excise_turnover_tax", False),
        ("(-) Less This Invoice Value", "less_this_invoice_value", False),
        ("Invoice Value", "invoice_value", False),
        ("MRP Round Off", "mrp_round_off", False),
        ("Net Invoice Value", "net_invoice_value", True),
        ("Total Invoice Value", "total_invoice_value", True),
    ]:
        finance_rows.append([
            Paragraph(label, small_bold if is_bold else small),
            Paragraph(
                fmt(totals.get(key)),
                ps(
                    f"fv_{key}",
                    fontSize=8,
                    alignment=TA_RIGHT,
                    fontName="Helvetica-Bold" if is_bold else "Helvetica",
                ),
            ),
        ])

    finance_rows.append([
        Paragraph("Retailer Credit Balance", small_bold),
        Paragraph(
            fmt(credit_balance),
            ps("credit_balance", fontSize=8, fontName="Helvetica-Bold", textColor=balance_color, alignment=TA_RIGHT),
        ),
    ])

    finance_table = Table(finance_rows, colWidths=[52 * mm, 38 * mm])
    finance_table.setStyle(TableStyle([
        ("ROWBACKGROUNDS", (0, 0), (-1, -2), [WHITE, ALT]),
        ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#EEF2F9")),
        ("GRID", (0, 0), (-1, -1), 0.35, RULE),
        ("LINEABOVE", (0, -1), (-1, -1), 0.8, NAVY),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))

    wrap = Table([[None, finance_table]], colWidths=[doc.width - 90 * mm, 90 * mm])
    wrap.setStyle(TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(wrap)

    doc.build(story)
    return output_path
