import os

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.platypus import BaseDocTemplate, Frame, HRFlowable, PageTemplate, Paragraph, Spacer, Table, TableStyle

W, H = A4
M = 13 * mm

INDIGO = colors.HexColor("#4f46e5")
INDIGO_MID = colors.HexColor("#818cf8")
INDIGO_BG = colors.HexColor("#eef2ff")
SLATE = colors.HexColor("#1e293b")
GREY = colors.HexColor("#64748b")
RULE = colors.HexColor("#e2e8f0")
ALT = colors.HexColor("#f8fafc")
TH_BG = colors.HexColor("#f1f5f9")
WHITE = colors.white
GREEN = colors.HexColor("#16a34a")


def ps(name, **kw):
    defaults = dict(fontName="Helvetica", fontSize=9, textColor=SLATE, leading=13)
    defaults.update(kw)
    return ParagraphStyle(name, **defaults)


def fmt(v):
    try:
        f = float(v)
        return f"{f:,.0f}" if f == int(f) else f"{f:,.2f}"
    except Exception:
        return str(v or "")


def draw_chrome(c: canvas.Canvas, doc):
    c.saveState()
    meta = doc._meta

    c.setFillColor(WHITE)
    c.rect(0, 0, W, H, fill=1, stroke=0)

    header_height = 20 * mm

    c.setFillColor(INDIGO)
    c.setFont("Helvetica-Bold", 15)
    c.drawString(M, H - 11 * mm, "Royal Wines")

    c.setFillColor(GREY)
    c.setFont("Helvetica", 8)
    c.drawString(M, H - 17 * mm, "Generated by Nagarjun Reddy")

    c.setFillColor(SLATE)
    c.setFont("Helvetica-Bold", 10)
    c.drawRightString(W - M, H - 11 * mm, "PRESENT STOCK REPORT")
    c.setFillColor(GREY)
    c.setFont("Helvetica", 8)
    c.drawRightString(W - M, H - 17 * mm, meta.get("generated_at", ""))

    c.setStrokeColor(INDIGO)
    c.setLineWidth(1.2)
    c.line(M, H - header_height, W - M, H - header_height)

    c.setStrokeColor(RULE)
    c.setLineWidth(0.5)
    c.line(M, 11 * mm, W - M, 11 * mm)
    c.setFillColor(GREY)
    c.setFont("Helvetica", 7.5)
    c.drawString(M, 7.5 * mm, "Royal Wines  .  Present Stock Report  .  Confidential")
    c.drawRightString(W - M, 7.5 * mm, f"Page {doc.page}")

    c.restoreState()


def build_present_stock_pdf(output_path: str, meta: dict, items: list):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    doc = BaseDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=M,
        rightMargin=M,
        topMargin=24 * mm,
        bottomMargin=18 * mm,
    )
    doc._meta = meta

    frame = Frame(
        doc.leftMargin,
        doc.bottomMargin,
        doc.width,
        doc.height,
        id="main",
        leftPadding=0,
        rightPadding=0,
        topPadding=0,
        bottomPadding=0,
    )
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=draw_chrome)])

    normal = ps("n")
    right = ps("r", alignment=TA_RIGHT)
    center = ps("c", alignment=TA_CENTER)
    th = ps("th", fontName="Helvetica-Bold", fontSize=8.5, alignment=TA_CENTER, textColor=SLATE)
    th_left = ps("thl", fontName="Helvetica-Bold", fontSize=8.5, alignment=TA_LEFT, textColor=SLATE)
    right_bold = ps("rb", fontName="Helvetica-Bold", alignment=TA_RIGHT)
    center_bold = ps("cb", fontName="Helvetica-Bold", alignment=TA_CENTER)
    label = ps("lbl", textColor=GREY, fontSize=9, leading=13)
    big = ps("big", fontName="Helvetica-Bold", fontSize=26, textColor=INDIGO, leading=30)
    amount_big = ps("smg", textColor=GREEN, fontName="Helvetica-Bold", fontSize=26, leading=30)

    story = []
    story.append(HRFlowable(width="100%", thickness=0.1, color=WHITE, spaceAfter=2))

    total_items = meta.get("total_items", len(items))
    total_bottles = sum(float(it.get("bottles", 0) or 0) for it in items)
    total_amount = meta.get("total_amount", sum(float(it.get("amount", 0) or 0) for it in items))

    third = doc.width / 3
    card_data = [
        ("Total Items", str(total_items), big),
        ("Total Bottles", fmt(total_bottles), big),
        ("Total Amount", f"Rs.{float(total_amount):,.0f}", amount_big),
    ]

    cards = Table(
        [
            [Paragraph(cd[0], label) for cd in card_data],
            [Paragraph(cd[1], cd[2]) for cd in card_data],
        ],
        colWidths=[third, third, third],
        rowHeights=[10 * mm, 24 * mm],
    )
    cards.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), INDIGO_BG),
        ("BOX", (0, 0), (-1, -1), 0.6, INDIGO),
        ("LINEAFTER", (0, 0), (1, -1), 0.4, INDIGO_MID),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(cards)
    story.append(Spacer(1, 10))

    rows = [[
        Paragraph("#", th),
        Paragraph("Brand No.", th),
        Paragraph("Brand Name", th_left),
        Paragraph("Pack Size", th),
        Paragraph("Pack\nType", th),
        Paragraph("Cases", th),
        Paragraph("Bottles", th),
        Paragraph("Rate /\nCase", th),
        Paragraph("Rate /\nBottle", th),
        Paragraph("Amount (Rs.)", th),
        Paragraph("Last Invoice\nDate", th),
    ]]

    for item in items:
        rows.append([
            Paragraph(str(item.get("sl_no", "")), center),
            Paragraph(str(item.get("brand_no", "")), center),
            Paragraph(item.get("brand_name", ""), normal),
            Paragraph(item.get("pack_size", ""), center),
            Paragraph(item.get("pack_type", ""), center),
            Paragraph(fmt(item.get("cases", 0)), center_bold),
            Paragraph(fmt(item.get("bottles", 0)), center_bold),
            Paragraph(fmt(item.get("rate_case", 0)), right),
            Paragraph(fmt(item.get("rate_btl", 0)), right),
            Paragraph(fmt(item.get("amount", 0)), right_bold),
            Paragraph(item.get("last_invoice_date", ""), center),
        ])

    table = Table(
        rows,
        colWidths=[8 * mm, 14 * mm, 54 * mm, 15 * mm, 11 * mm, 11 * mm, 13 * mm, 16 * mm, 16 * mm, 22 * mm, 20 * mm],
        repeatRows=1,
    )
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), TH_BG),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, ALT]),
        ("GRID", (0, 0), (-1, -1), 0.35, RULE),
        ("LINEBELOW", (0, 0), (-1, 0), 1.0, INDIGO),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(table)

    doc.build(story)
    return output_path


def write_present_stock_pdf(output_path, meta_rows, items_rows, summary_rows, title="Present Stock Report"):
    meta = {}
    for row in meta_rows or []:
        if len(row) < 2:
            continue
        key = str(row[0] or "").strip().lower()
        value = row[1]
        if key == "generated at":
            meta["generated_at"] = str(value or "")
        elif key == "total items":
            meta["total_items"] = int(value or 0)

    for row in summary_rows or []:
        if len(row) < 2:
            continue
        key = str(row[0] or "").strip().lower()
        value = row[1]
        if "total amount" in key:
            meta["total_amount"] = float(value or 0)

    items = []
    for index, row in enumerate(items_rows or []):
        if index == 0:
            continue
        items.append({
            "sl_no": row[0] if len(row) > 0 else "",
            "brand_no": row[1] if len(row) > 1 else "",
            "brand_name": str(row[2] if len(row) > 2 else ""),
            "pack_size": str(row[3] if len(row) > 3 else ""),
            "pack_type": str(row[4] if len(row) > 4 else ""),
            "cases": row[5] if len(row) > 5 else 0,
            "bottles": row[6] if len(row) > 6 else 0,
            "rate_case": row[7] if len(row) > 7 else 0,
            "rate_btl": row[8] if len(row) > 8 else 0,
            "amount": row[9] if len(row) > 9 else 0,
            "last_invoice_date": str(row[10] if len(row) > 10 else ""),
        })

    return build_present_stock_pdf(output_path, meta, items)


if __name__ == "__main__":
    meta = {
        "generated_at": "2026-03-19 01:23:10",
        "total_items": 41,
        "total_amount": 709450.0,
    }
    items = [
        {"sl_no": 1, "brand_no": "0546", "brand_name": "8PM PREMIUM BLACK WHISKY", "pack_size": "48/180ml", "pack_type": "G", "cases": 0, "bottles": 4, "rate_case": 10560, "rate_btl": 220, "amount": 880, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 2, "brand_no": "0546", "brand_name": "8PM PREMIUM BLACK WHISKY", "pack_size": "24/375ml", "pack_type": "G", "cases": 0, "bottles": 21, "rate_case": 10560, "rate_btl": 440, "amount": 9240, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 3, "brand_no": "0546", "brand_name": "8PM PREMIUM BLACK WHISKY", "pack_size": "12/750ml", "pack_type": "G", "cases": 0, "bottles": 10, "rate_case": 10560, "rate_btl": 880, "amount": 8800, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 4, "brand_no": "0596", "brand_name": "ANTIQUITY BLUE ULTRA PREMIUM WHISKY", "pack_size": "48/180ml", "pack_type": "G", "cases": 0, "bottles": 11, "rate_case": 17280, "rate_btl": 360, "amount": 3960, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 5, "brand_no": "0596", "brand_name": "ANTIQUITY BLUE ULTRA PREMIUM WHISKY", "pack_size": "12/750ml", "pack_type": "G", "cases": 0, "bottles": 5, "rate_case": 17400, "rate_btl": 1450, "amount": 7250, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 6, "brand_no": "1267", "brand_name": "ARTIC PURE VODKA", "pack_size": "12/750ml", "pack_type": "G", "cases": 0, "bottles": 1, "rate_case": 18240, "rate_btl": 1520, "amount": 1520, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 7, "brand_no": "7154", "brand_name": "BLACK & WHITE BLENDED SCOTCH WHISKY", "pack_size": "12/750ml", "pack_type": "G", "cases": 0, "bottles": 6, "rate_case": 24960, "rate_btl": 2080, "amount": 12480, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 8, "brand_no": "0672", "brand_name": "DIAMOND FINE WHISKY", "pack_size": "48/180ml", "pack_type": "G", "cases": 0, "bottles": 66, "rate_case": 5280, "rate_btl": 110, "amount": 7260, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 9, "brand_no": "5028", "brand_name": "HAYWARDS 5000 SUPER STRONG BEER", "pack_size": "12/650ml", "pack_type": "G", "cases": 0, "bottles": 984, "rate_case": 2280, "rate_btl": 190, "amount": 186960, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 10, "brand_no": "1756", "brand_name": "ICONIQ WHITE SELECT INTL GRAIN WHISKY", "pack_size": "96/90ml", "pack_type": "G", "cases": 0, "bottles": 58, "rate_case": 9600, "rate_btl": 100, "amount": 5800, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 11, "brand_no": "5016", "brand_name": "KING FISHER PREMIUM LAGER BEER", "pack_size": "12/650ml", "pack_type": "G", "cases": 0, "bottles": 163, "rate_case": 2160, "rate_btl": 180, "amount": 29340, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 12, "brand_no": "5017", "brand_name": "KING FISHER STRONG PREMIUM BEER", "pack_size": "12/650ml", "pack_type": "G", "cases": 0, "bottles": 436, "rate_case": 2280, "rate_btl": 190, "amount": 82840, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 13, "brand_no": "0019", "brand_name": "MCDOWELLS NO 1 LUXURY WHISKY", "pack_size": "96/90ml", "pack_type": "G", "cases": 0, "bottles": 39, "rate_case": 9600, "rate_btl": 100, "amount": 3900, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 14, "brand_no": "0019", "brand_name": "MCDOWELLS NO 1 LUXURY WHISKY", "pack_size": "48/180ml", "pack_type": "G", "cases": 0, "bottles": 39, "rate_case": 9120, "rate_btl": 190, "amount": 7410, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 15, "brand_no": "0019", "brand_name": "MCDOWELLS NO 1 LUXURY WHISKY", "pack_size": "24/375ml", "pack_type": "G", "cases": 0, "bottles": 21, "rate_case": 9120, "rate_btl": 380, "amount": 7980, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 16, "brand_no": "0798", "brand_name": "OAKSMITH GOLD INTL BLENDED WHISKY", "pack_size": "48/180ml", "pack_type": "G", "cases": 0, "bottles": 14, "rate_case": 17760, "rate_btl": 370, "amount": 5180, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 17, "brand_no": "0798", "brand_name": "OAKSMITH GOLD INTL BLENDED WHISKY", "pack_size": "24/375ml", "pack_type": "G", "cases": 0, "bottles": 8, "rate_case": 17760, "rate_btl": 740, "amount": 5920, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 18, "brand_no": "0645", "brand_name": "OFFICER S CHOICE BLUE PURE GRAIN WHISKY", "pack_size": "12/750ml", "pack_type": "G", "cases": 0, "bottles": 1, "rate_case": 9120, "rate_btl": 760, "amount": 760, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 19, "brand_no": "0110", "brand_name": "OFFICER'S CHOICE RESERVE WHISKY", "pack_size": "96/90ml", "pack_type": "G", "cases": 0, "bottles": 1171, "rate_case": 8640, "rate_btl": 90, "amount": 105390, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 20, "brand_no": "0110", "brand_name": "OFFICER'S CHOICE RESERVE WHISKY", "pack_size": "48/180ml", "pack_type": "G", "cases": 0, "bottles": 37, "rate_case": 7680, "rate_btl": 160, "amount": 5920, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 21, "brand_no": "0110", "brand_name": "OFFICER'S CHOICE RESERVE WHISKY", "pack_size": "12/750ml", "pack_type": "G", "cases": 0, "bottles": 21, "rate_case": 7680, "rate_btl": 640, "amount": 13440, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 22, "brand_no": "1536", "brand_name": "OLD ARTIC PURE VODKA NATURAL GREEN APPLE", "pack_size": "12/750ml", "pack_type": "G", "cases": 0, "bottles": 4, "rate_case": 18240, "rate_btl": 1520, "amount": 6080, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 23, "brand_no": "0382", "brand_name": "ROYAL CHALLENGE CLASSIC MALT WHISKY", "pack_size": "48/180ml", "pack_type": "G", "cases": 0, "bottles": 9, "rate_case": 14400, "rate_btl": 300, "amount": 2700, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 24, "brand_no": "0382", "brand_name": "ROYAL CHALLENGE CLASSIC MALT WHISKY", "pack_size": "24/375ml", "pack_type": "G", "cases": 0, "bottles": 3, "rate_case": 14400, "rate_btl": 600, "amount": 1800, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 25, "brand_no": "7355", "brand_name": "SEAGRAM S BLENDERS PRIDE RES. COLLECTION WHISKY", "pack_size": "12/750ml", "pack_type": "G", "cases": 0, "bottles": 2, "rate_case": 18720, "rate_btl": 1560, "amount": 3120, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 26, "brand_no": "0551", "brand_name": "SEAGRAM'S 100 PIPERS DX. BLENDED SCOTCH WHISKY", "pack_size": "12/750ml", "pack_type": "G", "cases": 0, "bottles": 9, "rate_case": 25920, "rate_btl": 2160, "amount": 19440, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 27, "brand_no": "0475", "brand_name": "SEAGRAM'S BLENDERS PRIDE SELECT PR. WHISKY", "pack_size": "48/180ml", "pack_type": "G", "cases": 0, "bottles": 4, "rate_case": 16320, "rate_btl": 340, "amount": 1360, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 28, "brand_no": "0258", "brand_name": "SEAGRAM'S IMPERIAL BLUE CLASSIC GRAIN WHISKY", "pack_size": "96/90ml", "pack_type": "G", "cases": 0, "bottles": 31, "rate_case": 9600, "rate_btl": 100, "amount": 3100, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 29, "brand_no": "0258", "brand_name": "SEAGRAM'S IMPERIAL BLUE CLASSIC GRAIN WHISKY", "pack_size": "48/180ml", "pack_type": "G", "cases": 0, "bottles": 29, "rate_case": 9120, "rate_btl": 190, "amount": 5510, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 30, "brand_no": "0258", "brand_name": "SEAGRAM'S IMPERIAL BLUE CLASSIC GRAIN WHISKY", "pack_size": "24/375ml", "pack_type": "G", "cases": 0, "bottles": 18, "rate_case": 9120, "rate_btl": 380, "amount": 6840, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 31, "brand_no": "0258", "brand_name": "SEAGRAM'S IMPERIAL BLUE CLASSIC GRAIN WHISKY", "pack_size": "12/750ml", "pack_type": "G", "cases": 0, "bottles": 7, "rate_case": 9120, "rate_btl": 760, "amount": 5320, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 32, "brand_no": "0259", "brand_name": "SEAGRAM'S ROYAL STAG BLENDED WHISKY", "pack_size": "12/1000ml", "pack_type": "G", "cases": 0, "bottles": 12, "rate_case": 14160, "rate_btl": 1180, "amount": 14160, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 33, "brand_no": "0259", "brand_name": "SEAGRAM'S ROYAL STAG BLENDED WHISKY", "pack_size": "96/90ml", "pack_type": "G", "cases": 0, "bottles": 134, "rate_case": 11520, "rate_btl": 120, "amount": 16080, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 34, "brand_no": "0259", "brand_name": "SEAGRAM'S ROYAL STAG BLENDED WHISKY", "pack_size": "48/180ml", "pack_type": "G", "cases": 0, "bottles": 17, "rate_case": 10560, "rate_btl": 220, "amount": 3740, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 35, "brand_no": "0259", "brand_name": "SEAGRAM'S ROYAL STAG BLENDED WHISKY", "pack_size": "24/375ml", "pack_type": "G", "cases": 0, "bottles": 15, "rate_case": 10560, "rate_btl": 440, "amount": 6600, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 36, "brand_no": "0259", "brand_name": "SEAGRAM'S ROYAL STAG BLENDED WHISKY", "pack_size": "12/750ml", "pack_type": "G", "cases": 0, "bottles": 10, "rate_case": 10560, "rate_btl": 880, "amount": 8800, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 37, "brand_no": "0426", "brand_name": "SIGNATURE ULTRA PREMIER GRAIN WHISKY", "pack_size": "6/2000ml", "pack_type": "P", "cases": 0, "bottles": 1, "rate_case": 21060, "rate_btl": 3510, "amount": 3510, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 38, "brand_no": "0426", "brand_name": "SIGNATURE ULTRA PREMIER GRAIN WHISKY", "pack_size": "48/180ml", "pack_type": "G", "cases": 0, "bottles": 18, "rate_case": 16320, "rate_btl": 340, "amount": 6120, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 39, "brand_no": "0426", "brand_name": "SIGNATURE ULTRA PREMIER GRAIN WHISKY", "pack_size": "12/750ml", "pack_type": "G", "cases": 0, "bottles": 3, "rate_case": 16320, "rate_btl": 1360, "amount": 4080, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 40, "brand_no": "7147", "brand_name": "SMIRNOFF ORANGE TWIST VODKA", "pack_size": "12/750ml", "pack_type": "G", "cases": 0, "bottles": 2, "rate_case": 15000, "rate_btl": 1250, "amount": 2500, "last_invoice_date": "30-Nov-2025"},
        {"sl_no": 41, "brand_no": "0256", "brand_name": "TI MANSION HOUSE GOLD WHISKY", "pack_size": "12/750ml", "pack_type": "G", "cases": 0, "bottles": 83, "rate_case": 11040, "rate_btl": 920, "amount": 76360, "last_invoice_date": "30-Nov-2025"},
    ]

    build_present_stock_pdf(
        "/mnt/user-data/outputs/present_stock_2026-03-18.pdf",
        meta,
        items,
    )
