import os

from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    HRFlowable,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

from .common import (
    GREY,
    NEG_RED,
    PAGE_HEIGHT,
    PAGE_WIDTH,
    POS_GREEN,
    ROW_ALT,
    RULE,
    SLATE,
    TABLE_HEAD_BG,
    WHITE,
    WINE,
    WINE_LIGHT,
    make_style,
)


def write_sell_report_pdf(output_path, meta_rows, items_rows, finance_rows, expense_rows, title="Sell Report"):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    generated_by = "Nagarjun"
    report_date = ""
    created_by = ""
    if meta_rows:
        for row in meta_rows:
            if len(row) < 2:
                continue
            key = str(row[0] or "").strip().lower()
            value = str(row[1] or "").strip()
            if key == "report_date":
                report_date = value
            elif key == "created_by":
                created_by = value
            elif key == "generated_by" and value:
                generated_by = value

    total_sell = 0.0
    final_balance = 0.0
    if finance_rows:
        for row in finance_rows:
            if len(row) < 2:
                continue
            key = str(row[0] or "").strip().lower()
            value = row[1]
            try:
                amount = float(value)
            except (TypeError, ValueError):
                amount = 0.0
            if key == "total_sell":
                total_sell = amount
            elif key == "final_balance":
                final_balance = amount

    def fmt(value):
        try:
            return f"{float(value):,.2f}"
        except (TypeError, ValueError):
            return str(value or "")

    data_items = []
    for index, row in enumerate(items_rows or []):
        if index == 0:
            continue
        data_items.append({
            "brand": str(row[0] if len(row) > 0 else ""),
            "size": str(row[1] if len(row) > 1 else ""),
            "sold_c": str(row[2] if len(row) > 2 and row[2] is not None else ""),
            "sold_b": str(row[3] if len(row) > 3 and row[3] is not None else ""),
            "amount": fmt(row[4] if len(row) > 4 else None),
        })

    header_height = 48 * mm
    footer_height = 18 * mm
    margin = 13 * mm

    def draw_chrome(canvas_obj: canvas.Canvas, doc):
        canvas_obj.saveState()

        canvas_obj.setFillColor(WHITE)
        canvas_obj.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, fill=1, stroke=0)

        header_y = PAGE_HEIGHT - header_height
        canvas_obj.setFillColor(WINE_LIGHT)
        canvas_obj.rect(0, header_y, PAGE_WIDTH, header_height, fill=1, stroke=0)

        canvas_obj.setFillColor(WINE)
        canvas_obj.rect(0, header_y, 4, header_height, fill=1, stroke=0)

        canvas_obj.setFillColor(WINE)
        canvas_obj.setFont("Helvetica-Bold", 18)
        canvas_obj.drawString(margin, PAGE_HEIGHT - 17 * mm, "Royal Wines")

        canvas_obj.setFillColor(GREY)
        canvas_obj.setFont("Helvetica", 7.5)
        canvas_obj.drawString(margin, PAGE_HEIGHT - 23 * mm, "Premium Spirits & Beverages Distribution")

        canvas_obj.setStrokeColor(WINE)
        canvas_obj.setLineWidth(0.5)
        canvas_obj.line(margin, PAGE_HEIGHT - 25.5 * mm, 78 * mm, PAGE_HEIGHT - 25.5 * mm)

        canvas_obj.setFillColor(SLATE)
        canvas_obj.setFont("Helvetica-Bold", 13)
        canvas_obj.drawRightString(PAGE_WIDTH - margin, PAGE_HEIGHT - 17 * mm, title.upper())

        canvas_obj.setFillColor(GREY)
        canvas_obj.setFont("Helvetica", 8)
        canvas_obj.drawRightString(PAGE_WIDTH - margin, PAGE_HEIGHT - 24 * mm, f"Date:  {report_date}")
        canvas_obj.drawRightString(PAGE_WIDTH - margin, PAGE_HEIGHT - 30 * mm, f"Generated By: {generated_by}")
        canvas_obj.drawRightString(PAGE_WIDTH - margin, PAGE_HEIGHT - 36 * mm, f"Created By:   {created_by}")

        canvas_obj.setStrokeColor(WINE)
        canvas_obj.setLineWidth(0.8)
        canvas_obj.line(0, header_y, PAGE_WIDTH, header_y)

        footer_y = 14 * mm
        canvas_obj.setStrokeColor(RULE)
        canvas_obj.setLineWidth(0.5)
        canvas_obj.line(margin, footer_y, PAGE_WIDTH - margin, footer_y)

        canvas_obj.setFillColor(GREY)
        canvas_obj.setFont("Helvetica", 7.5)
        canvas_obj.drawString(margin, footer_y - 5 * mm, "Royal Wines  |  Confidential Business Document")
        canvas_obj.drawRightString(PAGE_WIDTH - margin, footer_y - 5 * mm, f"Page {doc.page}")

        canvas_obj.restoreState()

    doc = BaseDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=margin,
        rightMargin=margin,
        topMargin=header_height + 10 * mm,
        bottomMargin=footer_height + 6 * mm,
    )
    frame = Frame(
        doc.leftMargin,
        doc.bottomMargin,
        doc.width,
        doc.height,
        id="main",
        leftPadding=0,
        rightPadding=0,
        topPadding=0,
        bottomPadding=0,
    )
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame], onPage=draw_chrome)])

    normal = make_style("normal")
    right = make_style("right", alignment=TA_RIGHT)
    head = make_style("head", fontName="Helvetica-Bold", alignment=TA_CENTER)
    section = make_style("section", fontName="Helvetica-Bold", fontSize=10, textColor=WINE, leading=16)
    grey = make_style("grey", textColor=GREY, alignment=TA_CENTER)
    grey_bold = make_style("grey_bold", fontName="Helvetica-Bold", alignment=TA_CENTER)
    label = make_style("label", fontName="Helvetica-Bold")
    value = make_style("value", fontName="Helvetica-Bold", alignment=TA_RIGHT)
    left = make_style("left", alignment=TA_LEFT)
    empty = make_style("empty", textColor=GREY, alignment=TA_LEFT)

    story = []

    story.append(Paragraph("Sales Breakdown", section))
    story.append(Spacer(1, 4))
    story.append(HRFlowable(width="100%", thickness=0.5, color=RULE, spaceAfter=6))

    rows = [[Paragraph(cell, head) for cell in ["Brand", "Size", "Sold (C)", "Sold (B)", "Amount (Rs.)"]]]
    for item in data_items:
        rows.append([
            Paragraph(item["brand"], normal),
            Paragraph(item["size"], normal),
            Paragraph(item["sold_c"], right),
            Paragraph(item["sold_b"], right),
            Paragraph(item["amount"], right),
        ])

    sales_table = Table(rows, colWidths=[82 * mm, 26 * mm, 20 * mm, 20 * mm, 35 * mm], repeatRows=1)
    sales_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), TABLE_HEAD_BG),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, ROW_ALT]),
        ("GRID", (0, 0), (-1, -1), 0.4, RULE),
        ("LINEBELOW", (0, 0), (-1, 0), 0.8, WINE),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(sales_table)
    story.append(Spacer(1, 22))

    story.append(Paragraph("Summary", section))
    story.append(Spacer(1, 4))
    story.append(HRFlowable(width="100%", thickness=0.5, color=RULE, spaceAfter=6))

    balance_style = make_style(
        "balance",
        fontName="Helvetica-Bold",
        fontSize=10,
        textColor=NEG_RED if final_balance < 0 else POS_GREEN,
        alignment=TA_RIGHT,
    )

    summary_table = Table(
        [
            [Paragraph("Total Sell", label), Paragraph(f"Rs. {total_sell:,.2f}", value)],
            [Paragraph("Final Balance", label), Paragraph(f"Rs. {final_balance:,.2f}", balance_style)],
        ],
        colWidths=[47.5 * mm, 47.5 * mm],
    )
    summary_table.setStyle(TableStyle([
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [ROW_ALT, WHITE]),
        ("GRID", (0, 0), (-1, -1), 0.4, RULE),
        ("LINEBELOW", (0, -1), (-1, -1), 0.8, WINE),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))

    summary_outer = Table([[None, summary_table]], colWidths=[doc.width - 95 * mm, 95 * mm])
    summary_outer.setStyle(TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(summary_outer)
    story.append(Spacer(1, 36))

    if expense_rows:
        story.append(Paragraph("Finance Section", section))
        story.append(Spacer(1, 4))
        story.append(HRFlowable(width="100%", thickness=0.5, color=RULE, spaceAfter=8))

        for section_data in expense_rows:
            title_text = str((section_data or {}).get("title") or "").strip()
            headers = list((section_data or {}).get("headers") or [])
            section_rows = list((section_data or {}).get("rows") or [])

            if title_text:
                story.append(Paragraph(
                    title_text,
                    make_style(f"finance_{title_text[:10]}", fontName="Helvetica-Bold", fontSize=9, textColor=SLATE, leading=14),
                ))
                story.append(Spacer(1, 4))

            if headers:
                table_rows = [[Paragraph(str(header or ""), head) for header in headers]]
                if section_rows:
                    for row in section_rows:
                        table_rows.append([
                            Paragraph(str(row[0] if len(row) > 0 else ""), left),
                            Paragraph(fmt(row[1] if len(row) > 1 else ""), right),
                        ])
                else:
                    table_rows.append([
                        Paragraph("No entries", empty),
                        Paragraph("0.00", right),
                    ])

                finance_table = Table(table_rows, colWidths=[doc.width - 42 * mm, 42 * mm], repeatRows=1)
                finance_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), TABLE_HEAD_BG),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, ROW_ALT]),
                    ("GRID", (0, 0), (-1, -1), 0.4, RULE),
                    ("LINEBELOW", (0, 0), (-1, 0), 0.8, WINE),
                    ("TOPPADDING", (0, 0), (-1, -1), 7),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ]))
                story.append(finance_table)
                story.append(Spacer(1, 12))

    signature_table = Table(
        [
            [HRFlowable(width=44 * mm, thickness=0.5, color=RULE), HRFlowable(width=44 * mm, thickness=0.5, color=RULE)],
            [Paragraph(generated_by, grey_bold), Paragraph(created_by, grey_bold)],
            [Paragraph("Generated By", grey), Paragraph("Authorised By", grey)],
        ],
        colWidths=[doc.width / 2, doc.width / 2],
    )
    signature_table.setStyle(TableStyle([
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(signature_table)

    doc.build(story)
    return output_path
